---
title: "R Notebook"
output: html_notebook
author:
  - Treasa Bency Biju Jose t.bijujose@ieee.org
---

## Packages

```{r, results = 'hide', message = FALSE, warning = FALSE}
library(tm)
library(stringr)
library(ggplot2)
library(wordcloud)
library(dplyr)
library(sets)
library(magrittr)
```

## Regions

```{r}
continent <- "africa" # c("africa", "asia", "oceania")
continent_by_row <- 135:190 # c(135:190, 91:134, 81:90)
anthems <- read.csv("anthems.csv")
```

## Data Cleaning

Remove whitespace, non-english words, and some predefined "bad words"

```{r}
anthems <- anthems[135:190, 5]
anthems %<>%
  trimws() %>%
  tolower() %>%
  removeWords(stopwords()) %>%
  removePunctuation() %>%
  removeWords(c("may", "thee", "thou", "thy",
                "say", "ever", "every", "across",
                "another", "many", "will", "cut", "always",
                "avoid", "one", "make", "let", "shall"))
```

## Tally Words

```{r}
data <- anthems %>%
  VectorSource() %>%
  Corpus() %>%
  DocumentTermMatrix() %>%
  as.matrix() %>%
  colSums() %>%
  sort(decreasing = TRUE) %>%
  as.data.frame() %>%
  tibble::rownames_to_column("word")

colnames(data) <- c("word", "count")
```

## Plot
```{r}
ggplot(head(data), aes(x = word, y = count)) +
  geom_bar(stat = "identity") +
  coord_flip()

wordcloud(data$word, data$count, random.order = FALSE, max.words = 25, colors = brewer.pal(9, "Spectral"))

```
